version: '3.8'
services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - node_modules_volume:/app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    tty: true
    # command: sh -c "cd app && npm run dev"
    ports:
      - 3000:3000

volumes:
  node_modules_volume: